# Generated by Django 3.2.7 on 2022-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userstatistic',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_wpm', models.IntegerField(default=0)),
                ('test_keystrokes', models.IntegerField(default=0)),
                ('test_accuracy', models.FloatField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
            ],
        ),
    ]
