# Generated by Django 3.2.7 on 2022-06-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0002_userstatistic_login_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistic',
            old_name='login_user',
            new_name='login_username',
        ),
    ]
